### ISSUE TITLE
Incorrect Price

### ISSUE THREAD

**Issue by robosung** [ConcurrenyLabs/aws-pricing-tools#15]
Just did a pricing comparison for RDS Aurora Postgresql db.r5.large and it came back with $5842 as annual cost. 

<img width="963" alt="Part_II__RDS_-_The_Ultimate_Guide_to_Saving_Money_with_AWS_Reserved__Anything__-_Concurrency_Labs" src="https://github.com/concurrencylabs/aws-pricing-tools/assets/471863/417e62ad-09a1-4276-a946-4663eef848d7">

It should be $2190 @ $0.25/hr.

**Comment by concurrencylabs** [comment]
Thank you for bringing this up. This was related by a. new record included in the AWS Price List index for the Aurora DB engine. It's been fixed and now the charts show the correct on demand pricing:

![image](https://github.com/concurrencylabs/aws-pricing-tools/assets/17148977/8ab36868-ba21-4bcc-a7fc-4cc8996887bd)
